### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [alvarezskinner/bwa-u4-feature-request#1]
### Criteria 1: Objective
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*:  Your objective is a great one.  It is always important to have a good error handling system to keep the user informed when things are going wrong in the app so they are not kept in the dark.

### Criteria 2: Background
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your background section is good.  It provides a detailed explanation of the pain point this feature is addressing.  You also gave a good summary of the overall functionality of the feature within the app.

### Criteria 3: Technical Design
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did well with your technical design section.  You described well how you would modify the existing state and leverage existing components to trigger manage/trigger the display of loading visuals as well as error states.  You also did well to think about adding a new notification component to notify users of the error that has occurred.  Very thorough!

### Criteria 4: Caveats
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did a good job thinking about the potential caveats of this feature.  You discussed the drawbacks of using links as buttons in your UI and addressed the additional work that would go into creating this new feature.  Nice work!

### Overall Score: 16/16
Overall, you did a great job with this feature request.  You chose a feature that would greatly improve the UX of the app and explained the necessity for this feature clearly and concisely.  You also did well in detailing the specific aspects of the technical implementation and what caveats you might encounter with your initial implementation.  Nicely done!

**Comment by alvarezskinner** [comment]
Thanks for the remarks! Really happy with the review!
